#nohup java -jar eureka.jar --spring.profiles.active=backup &
spring:
  profiles: backup 
server:
  port: 7999
eureka:
  environment: wrkenv
  instance:
    hostname: backuphost
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://master:123@masterIP:7998/eureka/
security:
  basic:
    enabled: true
  user:
    name: backup
    password: 123       
