spring:
  application:
    name: papy
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://almysql:6612/yaya?useSSL=true
    username: lllogin
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8         
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  
eureka:
  client:
    serviceUrl:
      defaultZone: http://master:123@localhost:7998/eureka,http://backup:123@localhost:7999/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}