spring:
  application:
    name: "zuul"
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://master:123@masterIP:7998/eureka/,http://backup:123@backupIP:7999/eureka/
security:
  basic:
    enabled: false

management:
  security:
    enabled: false

server:
  port: 7680

logging:
  level:
    root: INFO
    org.springframework.cloud.sleuth: DEBUG

zuul:
  routes:
    eureka:
      path: /springboot-admin
      url: http://127.0.0.1:1002
    api-papy:
      path: /api-papy/**
      service-id: papy
      sensitive-headers:
    test-papy:
      path: /test-papy/**
      service-id: test-papy
      sensitive-headers:            
    api-msg:
      path: /api-msg/**
      service-id: msg
    test-msg:
      path: /test-msg/**
      service-id: test-msg      