spring:
  application:
    name: "zuul"

eureka:
  instance:
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: http://master:123@118.89.29.111:7998/eureka/,http://backup:123@118.89.29.111:7999/eureka/


security:
  basic:
    enabled: false

management:
  security:
    enabled: false

server:
  port: 8040

logging:
  level:
    root: INFO
    org.springframework.cloud.sleuth: DEBUG

zuul:
  routes:
    api-a:
      path: /api-papy/**
      service-id: papy
      sensitive-headers:
    api-b:
      path: /api-msg/**
      service-id: msg